### PR TITLE
Flyer for hangout at FreeGeek

### PR DESCRIPTION
**Pull request by dasanchez**
PDF and Inkscape SVG for the flyer we gave out at the Sept 29 hangout.

### CODE REVIEW

**Review by makew0rld — APPROVED** [review]

**Review by Shrinks99 — CHANGES_REQUESTED** [review]
I can't seem to view the text on the SVG.  PDF looks fine but the SVG doesn't actually look like it includes it?  Are there any special export settings regarding text on Inkscape?  If the text is there but I don't have the font it should show in the default font but I've just got nothing.  This persists in the browser view on GitHub as well.

screen shot 2018-10-07 at 12 44 09 pm

We should also assemble a folder with all the free fonts that we use in it (I will do this!)  This document looks like it was set in Work Sans, is that correct?

**Comment by dasanchez** [comment]
@Shrinks99 yup, it is Work Sans.
I tried "plain SVG" and "optimized SVG", both of them also fail to render text in the browser 😕 
I added a file with all the text objects converted to paths- the file is 512kB now, but the text is displayed now.

**Comment by Shrinks99** [comment]
@dasanchez You tried this: https://inkscape.org/en/learn/faq/#flowed-text-doesnt-show-exported-file ??  Would be a nice alternative to having two files, especially because a PDF is already a vector format and usually I'd like to keep it down to one working file and one deliverable format for this kind of thing.  If that doesn't work then I'll approve it without the converted to outlines SVG but I'd also rather maintain compatibility if possible.

Really putting ya through the motions on this one, sorry!

**Comment by dasanchez** [comment]
@Shrinks99 thanks for looking into it! I think that fix from the FAQ page worked, can you check?

_Really putting ya through the motions on this one, sorry!_
It's all good, I'm all for compatibility and less files to worry about 👍

**Review by Shrinks99 — APPROVED** [review]
Looks good to me, approved!

**Pull request merged**
